spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.11:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 111111

mybatis:
  type-aliases-package: com.neil.mybatis.pojo
  mapper-locations: classpath:/mappers/*.xml
